trigger:
  - main 


pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: NetlifyVariables # Chứa: NETLIFY_AUTH_TOKEN, NETLIFY_SITE_ID
- group: SONAR_PROJECT    # Chứa: SONAR_ORG, SONAR_PROJECT_KEY, SONAR_TOKEN

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'


- script: |
    npm ci
  displayName: 'Install dependencies'


- script: |
    npx sonarqube-scanner \
      -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
      -Dsonar.organization=$(SONAR_ORG) \
      -Dsonar.login=$(SONAR_TOKEN) \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.sources=. \
      -Dsonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/build/**,**/public/**,**/coverage/**,**/*.config.js,**/*.config.mjs,**/next-env.d.ts \
      -Dsonar.tests=. \
      -Dsonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx
  displayName: 'Run SonarCloud Scan'

- script: |
    npm run build
  displayName: 'Build Next.js'


- script: |
    npm install -g netlify-cli
    netlify deploy --dir=out --prod
  env:
    NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
  displayName: 'Deploy to Netlify Production'