trigger:
- dev

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: VercelVariables-DEV
- group: BACKEND_API_URL

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'


- script: |
    echo "Backend URL: $(DEV)"
    npm install -g vercel
    vercel deploy --prod --token=$(VERCEL_TOKEN) --yes -e NEXT_PUBLIC_API_URL=$(DEV)
  env:
    VERCEL_ORG_ID: $(VERCEL_ORG_ID)
    VERCEL_PROJECT_ID: $(VERCEL_PROJECT_ID)
  displayName: 'Deploy to Vercel DEV'